In [245]:
## import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [246]:
data = pd.read_csv('all_month.csv')
data

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2025-01-16T02:09:21.820Z,34.044667,-117.133333,6.41,1.39,ml,60.0,29.0,0.01965,0.17,...,2025-01-16T02:14:01.618Z,"3 km S of Mentone, CA",earthquake,0.13,0.320,0.174000,27.0,automatic,ci,ci
1,2025-01-16T01:59:22.210Z,18.022667,-66.832500,16.26,2.42,md,12.0,131.0,0.06051,0.22,...,2025-01-16T02:07:21.980Z,"2 km SE of Yauco, Puerto Rico",earthquake,0.50,0.880,0.075361,5.0,reviewed,pr,pr
2,2025-01-16T01:55:52.520Z,38.831333,-122.821335,2.27,0.48,md,9.0,129.0,0.01184,0.01,...,2025-01-16T01:57:28.177Z,"8 km NNW of The Geysers, CA",earthquake,0.47,0.830,0.280000,9.0,automatic,nc,nc
3,2025-01-16T01:49:24.210Z,18.254500,-66.429000,39.02,2.30,md,10.0,117.0,0.08961,0.07,...,2025-01-16T02:00:19.900Z,"5 km NW of Orocovis, Puerto Rico",earthquake,0.52,0.700,0.035800,6.0,reviewed,pr,pr
4,2025-01-16T01:49:15.310Z,36.446167,-121.008163,0.87,1.66,md,7.0,125.0,0.04118,0.06,...,2025-01-16T01:50:51.945Z,"15 km SE of Pinnacles, CA",earthquake,0.47,1.020,0.040000,6.0,automatic,nc,nc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9059,2024-12-17T02:34:00.795Z,-17.650800,168.123800,35.00,4.20,mb,10.0,197.0,4.63500,0.81,...,2025-01-14T23:50:05.040Z,"22 km WNW of Port-Vila, Vanuatu",earthquake,12.71,1.984,0.263000,4.0,reviewed,us,us
9060,2024-12-17T02:27:19.306Z,-52.745500,25.891800,10.00,4.60,mb,10.0,116.0,20.68300,0.68,...,2025-01-14T23:38:45.040Z,south of Africa,earthquake,15.86,1.948,0.182000,9.0,reviewed,us,us
9061,2024-12-17T02:24:47.960Z,38.839500,-122.807503,2.24,1.02,md,15.0,55.0,0.01344,0.01,...,2024-12-17T02:52:17.617Z,"8 km WNW of Cobb, CA",earthquake,0.27,0.650,0.270000,16.0,automatic,nc,nc
9062,2024-12-17T02:24:14.990Z,38.832668,-122.817497,1.78,1.34,md,26.0,66.0,0.01093,0.02,...,2024-12-17T04:17:24.156Z,"8 km NNW of The Geysers, CA",earthquake,0.19,0.320,0.140000,28.0,automatic,nc,nc
9063,2024-12-17T02:20:54.900Z,39.695167,-110.833667,-3.49,2.04,md,8.0,205.0,0.07863,0.18,...,2024-12-17T15:01:54.030Z,"2 km NE of Helper, Utah",earthquake,1.15,1.310,0.377712,8.0,reviewed,uu,uu

In [247]:
#information about the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9064 entries, 0 to 9063
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   time             9064 non-null   object
 1   latitude         9064 non-null   float64
 2   longitude        9064 non-null   float64
 3   depth            9064 non-null   float64
 4   mag              9064 non-null   float64
 5   magType          9064 non-null   object
 6   nst              7590 non-null   float64
 7   gap              7590 non-null   float64
 8   dmin             7588 non-null   float64
 9   rms              9062 non-null   float64
 10  net              9064 non-null   object
 11  id               9064 non-null   object
 12  updated          9064 non-null   object
 13  place            9064 non-null   object
 14  type             9064 non-null   object
 15  horizontalError  6642 non-null   float64
 16  depthError       9063 non-null   float64
 17  magError         7569 non-null   float64
 18  magNst           7587 non-null   float64
 19  status           9064 non-null   object
 20  locationSource   9064 non-null   object
 21  magSource        9064 non-null   object
dtypes: float64(12), object(10)
memory usage: 1.5+ MB

In [248]:
#checking for missing values
data.isnull()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9059,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9060,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9061,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9062,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9063,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [249]:
#sum of missing values
data.isnull().sum()

time                  0
latitude              0
longitude             0
depth                 0
mag                   0
magType               0
nst                1474
gap                1474
dmin               1476
rms                   2
net                   0
id                    0
updated               0
place                 0
type                  0
horizontalError    2422
depthError            1
magError           1495
magNst             1477
status                0
locationSource        0
magSource             0
dtype: int64

In [250]:
#basic statistics
data.describe()

,latitude,longitude,depth,mag,nst,gap,dmin,rms,horizontalError,depthError,magError,magNst
count,9064.000000,9064.000000,9064.000000,9064.000000,7590.000000,7590.000000,7588.000000,9062.000000,6642.000000,9063.000000,7569.000000,7587.000000
mean,40.091383,-109.540362,19.675905,1.561951,22.434256,117.710217,0.530965,0.266731,1.895567,2.283849,0.192650,17.001582
std,18.860981,68.238047,48.640784,1.320088,20.755778,64.495508,1.938568,0.270947,3.431114,5.597603,0.119073,22.022925
min,-62.505900,-179.841600,-3.490000,-1.890000,0.000000,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,33.575375,-150.929050,2.400000,0.780000,9.000000,69.000000,0.017000,0.090000,0.270000,0.500000,0.118000,7.000000
50%,38.825001,-121.864000,6.868900,1.400000,15.000000,105.000000,0.062905,0.160000,0.450000,0.860000,0.175743,10.000000
75%,58.173500,-114.452792,12.982500,2.000000,28.000000,148.472500,0.128525,0.354675,1.030000,1.864500,0.238174,21.000000
max,75.758100,179.991600,642.980000,7.100000,252.000000,344.000000,50.218000,3.050000,30.650000,228.600000,2.970000,357.000000

In [251]:
# Identify duplicate rows
duplicates = data.duplicated()
# Print Total number of duplicate rows
print(duplicates.sum())

0

In [252]:
# Ensure each column has the appropriate data type

# Convert time to datetime format
# Ensures that invalid parsing results in NaT
data['time'] = pd.to_datetime(data['time'], errors='coerce')

In [253]:
# Convert updated to datetime format
# Ensures that invalid parsing results in NaT
data['updated'] = pd.to_datetime(data['time'], errors='coerce')

In [254]:
#sum of missing values
data.isnull().sum()

time                  0
latitude              0
longitude             0
depth                 0
mag                   0
magType               0
nst                1474
gap                1474
dmin               1476
rms                   2
net                   0
id                    0
updated               0
place                 0
type                  0
horizontalError    2422
depthError            1
magError           1495
magNst             1477
status                0
locationSource        0
magSource             0
dtype: int64

In [255]:
#information about the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9064 entries, 0 to 9063
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   time             9064 non-null   datetime64[ns, UTC]
 1   latitude         9064 non-null   float64
 2   longitude        9064 non-null   float64
 3   depth            9064 non-null   float64
 4   mag              9064 non-null   float64
 5   magType          9064 non-null   object
 6   nst              7590 non-null   float64
 7   gap              7590 non-null   float64
 8   dmin             7588 non-null   float64
 9   rms              9062 non-null   float64
 10  net              9064 non-null   object
 11  id               9064 non-null   object
 12  updated          9064 non-null   datetime64[ns, UTC]
 13  place            9064 non-null   object
 14  type             9064 non-null   object
 15  horizontalError  6642 non-null   float64
 16  depthError       9063 non-null   float64
 17  magError         7569 non-null   float64
 18  magNst           7587 non-null   float64
 19  status           9064 non-null   object
 20  locationSource   9064 non-null   object
 21  magSource        9064 non-null   object
dtypes: datetime64[ns, UTC](2), float64(12), object(8)
memory usage: 1.5+ MB

In [256]:
data

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2025-01-16 02:09:21.820000+00:00,34.044667,-117.133333,6.41,1.39,ml,60.0,29.0,0.01965,0.17,...,2025-01-16 02:09:21.820000+00:00,"3 km S of Mentone, CA",earthquake,0.13,0.320,0.174000,27.0,automatic,ci,ci
1,2025-01-16 01:59:22.210000+00:00,18.022667,-66.832500,16.26,2.42,md,12.0,131.0,0.06051,0.22,...,2025-01-16 01:59:22.210000+00:00,"2 km SE of Yauco, Puerto Rico",earthquake,0.50,0.880,0.075361,5.0,reviewed,pr,pr
2,2025-01-16 01:55:52.520000+00:00,38.831333,-122.821335,2.27,0.48,md,9.0,129.0,0.01184,0.01,...,2025-01-16 01:55:52.520000+00:00,"8 km NNW of The Geysers, CA",earthquake,0.47,0.830,0.280000,9.0,automatic,nc,nc
3,2025-01-16 01:49:24.210000+00:00,18.254500,-66.429000,39.02,2.30,md,10.0,117.0,0.08961,0.07,...,2025-01-16 01:49:24.210000+00:00,"5 km NW of Orocovis, Puerto Rico",earthquake,0.52,0.700,0.035800,6.0,reviewed,pr,pr
4,2025-01-16 01:49:15.310000+00:00,36.446167,-121.008163,0.87,1.66,md,7.0,125.0,0.04118,0.06,...,2025-01-16 01:49:15.310000+00:00,"15 km SE of Pinnacles, CA",earthquake,0.47,1.020,0.040000,6.0,automatic,nc,nc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9059,2024-12-17 02:34:00.795000+00:00,-17.650800,168.123800,35.00,4.20,mb,10.0,197.0,4.63500,0.81,...,2024-12-17 02:34:00.795000+00:00,"22 km WNW of Port-Vila, Vanuatu",earthquake,12.71,1.984,0.263000,4.0,reviewed,us,us
9060,2024-12-17 02:27:19.306000+00:00,-52.745500,25.891800,10.00,4.60,mb,10.0,116.0,20.68300,0.68,...,2024-12-17 02:27:19.306000+00:00,south of Africa,earthquake,15.86,1.948,0.182000,9.0,reviewed,us,us
9061,2024-12-17 02:24:47.960000+00:00,38.839500,-122.807503,2.24,1.02,md,15.0,55.0,0.01344,0.01,...,2024-12-17 02:24:47.960000+00:00,"8 km WNW of Cobb, CA",earthquake,0.27,0.650,0.270000,16.0,automatic,nc,nc
9062,2024-12-17 02:24:14.990000+00:00,38.832668,-122.817497,1.78,1.34,md,26.0,66.0,0.01093,0.02,...,2024-12-17 02:24:14.990000+00:00,"8 km NNW of The Geysers, CA",earthquake,0.19,0.320,0.140000,28.0,automatic,nc,nc
9063,2024-12-17 02:20:54.900000+00:00,39.695167,-110.833667,-3.49,2.04,md,8.0,205.0,0.07863,0.18,...,2024-12-17 02:20:54.900000+00:00,"2 km NE of Helper, Utah",earthquake,1.15,1.310,0.377712,8.0,reviewed,uu,uu

In [257]:
#Create date column extracting only the yyyy-mm-dd from the 'time' column
data['date'] = pd.to_datetime(data['time']).dt.date

#Create hour column extracting on the hh from the 'time' column
data['hour'] = pd.to_datetime(data['time']).dt.hour

In [258]:
data.groupby(['hour']).count()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource,date
hour,,,,,,,,,,,,,,,,,,,,,
0,343,343,343,343,343,343,296,296,296,343,...,343,343,257,343,295,296,343,343,343,343
1,354,354,354,354,354,354,302,302,302,354,...,354,354,271,354,301,302,354,354,354,354
2,383,383,383,383,383,383,330,330,330,383,...,383,383,301,383,329,330,383,383,383,383
3,453,453,453,453,453,453,372,372,372,453,...,453,453,322,453,370,372,453,453,453,453
4,403,403,403,403,403,403,337,337,337,403,...,403,403,299,403,337,337,403,403,403,403
5,369,369,369,369,369,369,298,298,298,369,...,369,369,257,369,297,297,369,369,369,369
6,379,379,379,379,379,379,314,314,314,378,...,379,379,264,378,313,313,379,379,379,379
7,381,381,381,381,381,381,316,316,316,381,...,381,381,273,381,316,316,381,381,381,381
8,433,433,433,433,433,433,360,360,360,433,...,433,433,323,433,360,360,433,433,433,433
9,417,417,417,417,417,417,361,361,361,417,...,417,417,319,417,361,361,417,417,417,417
10,367,367,367,367,367,367,298,298,298,367,...,367,367,259,367,298,298,367,367,367,367
11,377,377,377,377,377,377,313,313,313,377,...,377,377,268,377,310,313,377,377,377,377
12,373,373,373,373,373,373,316,316,315,373,...,373,373,270,373,315,316,373,373,373,373
13,364,364,364,364,364,364,298,298,298,364,...,364,364,257,364,297,298,364,364,364,364
14,367,367,367,367,367,367,301,301,301,367,...,367,367,249,367,299,301,367,367,367,367
15,422,422,422,422,422,422,356,356,356,422,...,422,422,315,422,355,356,422,422,422,422
16,322,322,322,322,322,322,275,275,275,322,...,322,322,246,322,273,275,322,322,322,322
17,398,398,398,398,398,398,338,338,338,398,...,398,398,293,398,338,338,398,398,398,398
18,352,352,352,352,352,352,297,297,297,352,...,352,352,261,352,296,297,352,352,352,352
19,405,405,405,405,405,405,348,348,348,405,...,405,405,306,405,348,348,405,405,405,405
20,388,388,388,388,388,388,333,333,333,388,...,388,388,293,388,330,332,388,388,388,388
21,362,362,362,362,362,362,295,295,295,362,...,362,362,262,362,294,294,362,362,362,362
22,314,314,314,314,314,314,257,257,256,313,...,314,314,227,314,258,258,314,314,314,314
23,338,338,338,338,338,338,279,279,279,338,...,338,338,250,338,279,279,338,338,338,338

In [259]:
data

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource,date,hour
0,2025-01-16 02:09:21.820000+00:00,34.044667,-117.133333,6.41,1.39,ml,60.0,29.0,0.01965,0.17,...,earthquake,0.13,0.320,0.174000,27.0,automatic,ci,ci,2025-01-16,2
1,2025-01-16 01:59:22.210000+00:00,18.022667,-66.832500,16.26,2.42,md,12.0,131.0,0.06051,0.22,...,earthquake,0.50,0.880,0.075361,5.0,reviewed,pr,pr,2025-01-16,1
2,2025-01-16 01:55:52.520000+00:00,38.831333,-122.821335,2.27,0.48,md,9.0,129.0,0.01184,0.01,...,earthquake,0.47,0.830,0.280000,9.0,automatic,nc,nc,2025-01-16,1
3,2025-01-16 01:49:24.210000+00:00,18.254500,-66.429000,39.02,2.30,md,10.0,117.0,0.08961,0.07,...,earthquake,0.52,0.700,0.035800,6.0,reviewed,pr,pr,2025-01-16,1
4,2025-01-16 01:49:15.310000+00:00,36.446167,-121.008163,0.87,1.66,md,7.0,125.0,0.04118,0.06,...,earthquake,0.47,1.020,0.040000,6.0,automatic,nc,nc,2025-01-16,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9059,2024-12-17 02:34:00.795000+00:00,-17.650800,168.123800,35.00,4.20,mb,10.0,197.0,4.63500,0.81,...,earthquake,12.71,1.984,0.263000,4.0,reviewed,us,us,2024-12-17,2
9060,2024-12-17 02:27:19.306000+00:00,-52.745500,25.891800,10.00,4.60,mb,10.0,116.0,20.68300,0.68,...,earthquake,15.86,1.948,0.182000,9.0,reviewed,us,us,2024-12-17,2
9061,2024-12-17 02:24:47.960000+00:00,38.839500,-122.807503,2.24,1.02,md,15.0,55.0,0.01344,0.01,...,earthquake,0.27,0.650,0.270000,16.0,automatic,nc,nc,2024-12-17,2
9062,2024-12-17 02:24:14.990000+00:00,38.832668,-122.817497,1.78,1.34,md,26.0,66.0,0.01093,0.02,...,earthquake,0.19,0.320,0.140000,28.0,automatic,nc,nc,2024-12-17,2
9063,2024-12-17 02:20:54.900000+00:00,39.695167,-110.833667,-3.49,2.04,md,8.0,205.0,0.07863,0.18,...,earthquake,1.15,1.310,0.377712,8.0,reviewed,uu,uu,2024-12-17,2